//written by @joseCao5 on SuperCollider 3.6.3 | Linux
//mixfuckedup.net
//Dic2013/ene2014 @ Puerto Morelos Q. Roo Mx.
//////////////////////////////////////////////////////////////////////
//CaosBox v 0.08
//////////////////////////////////////////////////////////////////////
// * evalua todo la siguiente linea: / evaluate all in the next line:
(
s.waitForBoot{
	 ~url="/home/josecao5/Documents/caosbox/";/* <--- Change for your local URL*/
	(~url +/+ "CB/CaosBox-load-v0.08.scd").load};/* <-- don't change this one */
);
//end of file